[tool.poetry]
name = "project"
version = "0.1.0"
description = ""
authors = ["ShahirAmpera <Shahr.shaik@amperatech.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.62.0"
pandas = "^3.0.5"
psycopg = {extras = ["binary"], version = "^3.3.4"}
gradio = "^6.26.0"
matplotlib = "^3.11.1"
plotly = "^7.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
