[tool.poetry]
name = "session4"
version = "1.0"
description = "n"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
psycopg = {extras = ["binay"], version = "^3.3.4"}
streamlit = "^1.62.0"
matplotlib = "^3.11.1"
pandas = "^3.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
